config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "artworks#index"

  resources :cards, only: [:new, :create, :destroy]

  resources :contacts, only: [:index]

  resources :donation_projects, only: [:index, :new, :create]

  resources :users, only: [:show] do
    member do
      get 'favorite'
    end
  end

  resources :artists, only: [:index, :new, :create, :edit, :update, :show] do
    collection do
      post 'search'
    end
  end

  resources :artworks do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
  end

  resources :donation_project_rooms, only: [:show] do
    resources :room_messages, only: [:create]
  end

  mount ActionCable.server => '/cable' #追加
  
end

app/models/artist.rb
class Artist < ApplicationRecord
  
  belongs_to :user
  belongs_to :donation_project
  has_many :artworks, dependent: :destroy
  has_many :room_messages
  
  has_one_attached :image

  with_options presence: true do
    validates :artist_name, uniqueness: true
    validates :image, presence: { message: 'を選択してください' }
  end

  def self.search(search)

    #文字列部分一致で検索
    Artist.where(['artist_name LIKE ?', "%#{search}%"] )
   
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_artist, only: [:edit, :show, :update]
  before_action :search_artwork, only: [:index, :search, :show]

  def index
    @artists = Artist.all.order(:artist_name)

  end

  def new
    @artist = Artist.new

  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.valid?
      @artist.save

      redirect_to root_path

    else
      render :new

    end
  end

  def edit
    unless current_user.id == @artist.user.id
      redirect_to root_path
      
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to root_path

    else
      render :edit

    end
  end

  def show
    @artworks = @artist.artworks.all
    @donation_project = DonationProject.find_by(id: @artist.donation_project_id)

  end

  def search

    #ビューファイルへ表示するため検索条件を保持
    @keyword = params[:keyword]

    #パラメータから送られてきた検索条件で検索
    @results = Artist.search(@keyword)

  end

  private

  def artist_params
    params.require(:artist).permit(:artist_name, :donation_project_id, :affiliation, :personal_history, :reason_for_support_activities, :artist_message, :image).merge(user_id: current_user.id)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def search_artwork

    # 検索オブジェクトを生成
    @a = Artwork.ransack(params[:q])  

    #ActiveHachに定義されたidが０以外の各値を変数に格納
    @category = Category.where.not(id: 0)
    @main_color = MainColor.where.not(id: 0)
    @motif = Motif.where.not(id: 0)
    @feeling = Feeling.where.not(id: 0)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/edit.html.erb
<%= render "shared/second-header" %>

<div id="artist-edit-background-image">

  <div class="artist-contents">
    <div class="svgSample1">
    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
      <defs>
        <text dy="0.4em" id="outTextx">アーティスト情報編集</text>
      </defs>
      <use x="50%" y="50%" xlink:href="#outTextx"></use>
      <use x="50%" y="50%" xlink:href="#outTextx"></use>
    </svg>
    </div>

    アーティスト情報を編集しましょう。自分の作品に興味を持ってもらるようなプロフィールを作成しましょう。

  <%= form_with model: @artist, local: true do |f| %>

    <%= render 'shared/error_messages', model: @artist %>

    <div class="field">
    <%= f.label :image, "アーティスト写真", class:"label" %><br />
    <%= f.file_field :image, id:"content-image" %>
    <div id="image-list"></div>
    </div>

    <div class="field">
    <%= f.label :donation_project_id, "支援プロジェクト名", class:"label" %><br />
    <%= f.collection_select :donation_project_id, DonationProject.where("current_amount < target_amount"), :id, :project_name, include_blank: '--' %>
    </div>

    <div class="field">
    <%= f.label :artist_name, "アーティスト名", class:"label" %><br />
    <%= f.text_field :artist_name, class:"artist-name-textarea", placeholder:"例) 岡本太郎", maxlength:"7" %>
    </div>

    <div class="field">
    <%= f.label :affiliation, "所属", class:"label" %><br />
    <%= f.text_field :affiliation, class:"affiliation-textarea", placeholder:"例) 現代芸術アトリエ", maxlength:"10" %>
    </div>

    <div class="field">
    <%= f.label :personal_history, "経緯・経歴", class:"label" %><br />
    <%= f.text_area :personal_history, class:"personal-history-textarea", placeholder:"例) 趣味程度ですが、子供の頃から絵を描くことが好きで大人になった今でも描き続けています", maxlength:"150" %>
    </div>

    <div class="field">
    <%= f.label :reason_for_support_activities, "支援活動に興味をもった理由", class:"label" %><br />
    <%= f.text_area :reason_for_support_activities, class:"reason-for-support-activities-textarea", placeholder:"例) 自分の作った作品を通して誰かの助けになれることはとてもすばらしいことです", maxlength:"150" %>
    </div>

    <div class="field">
    <%= f.label :artist_message, "メッセージ", class:"label" %><br />
    <%= f.text_area :artist_message, class:"artist-message-textarea", placeholder:"例) 世界中に支援の輪を広げていきましょう！", maxlength:"150" %>
    </div>

    <%= f.submit "変更する" ,class:"submit-btn" %>

  <% end %>
  </div>

</div>

<%= render "shared/footer" %>

app/views/artists/index.html.erb
<%= render "shared/header" %>

<div id="artist-index-background-image">

<div class="page-title">SUPPORT ARTISTS</div>

<div class="grid">
  <% if @artists.present? %>
    <% @artists.each do |artist| %>
      <div class="artist"> 

      <%= link_to image_tag(artist.image, class: "artist-img"), artist_path(artist.id) if artist.image.attached? %>

      <p class="property">name: <span class="bold"><%= artist.artist_name %></span></p>

      </div>
    <% end %>
  <% else %>
    <div class="content-non">アーティストが登録されていません。</div>
  <% end %>
</div>

</div>

<%= render "shared/footer" %>

app/views/artists/new.html.erb
<%= render "shared/second-header" %>

<div id="artist-new-background-image">

  <div class="artist-contents">
    <div class="svgSample1">
    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
      <defs>
        <text dy="0.4em" id="outTextx">アーティスト情報登録</text>
      </defs>
      <use x="50%" y="50%" xlink:href="#outTextx"></use>
      <use x="50%" y="50%" xlink:href="#outTextx"></use>
    </svg>
    </div>

    アーティスト情報を入力しましょう。自分の作品に興味を持ってもらるようなプロフィールを作成しましょう。

    <%= form_with model: @artist, local: true do |f| %>

    <%= render 'shared/error_messages', model: @artist %>

    <div class="field">
    <%= f.label :image, "アーティスト写真" , class:"label"%><br />
    <%= f.file_field :image, id:"content-image" %>
    <div id="image-list"></div>
    </div>

    <div class="field">
    <%= f.label :donation_project_id, "支援プロジェクト名" , class:"label"%><br />
    <%= f.collection_select :donation_project_id, DonationProject.where("current_amount < target_amount"), :id, :project_name, include_blank: '--', class:"select-box" %>
    </div>

    <div class="field">
    <%= f.label :artist_name, "アーティスト名" , class:"label"%><br />
    <%= f.text_field :artist_name, class:"artist-name-textarea", placeholder:"例) 岡本太郎", maxlength:"7" %>
    </div>

    <div class="field">
    <%= f.label :affiliation, "所属" , class:"label"%><br />
    <%= f.text_field :affiliation, class:"affiliation-textarea", placeholder:"例) 現代芸術アトリエ", maxlength:"10" %>
    </div>

    <div class="field">
    <%= f.label :personal_history, "経緯・経歴" , class:"label"%><br />
    <%= f.text_area :personal_history, class:"personal-history-textarea", placeholder:"例) 趣味程度ですが、子供の頃から絵を描くことが好きで大人になった今でも描き続けています", maxlength:"150" %>
    </div>

    <div class="field">
    <%= f.label :reason_for_support_activities, "支援活動に興味をもった理由" , class:"label"%><br />
    <%= f.text_area :reason_for_support_activities, class:"reason-for-support-activities-textarea", placeholder:"例) 自分の作った作品を通して誰かの助けになれることはとてもすばらしいことです", maxlength:"150" %>
    </div>

    <div class="field">
    <%= f.label :artist_message, "メッセージ" , class:"label"%><br />
    <%= f.text_area :artist_message, class:"artist-message-textarea", placeholder:"例) 世界中に支援の輪を広げていきましょう！", maxlength:"150" %>
    </div>

    <%= f.submit "登録する" ,class:"submit-btn" %>

  <% end %>
  </div>

</div>

<%= render "shared/footer" %>

app/views/artists/search.html.erb
<%= render "shared/header" %>

<div id="artwork-search-background-image">

<div class="page-title">keyword”<%= @keyword %>”,   ARTIST SEARCH RESULT</div>

<div class="grid">
  <% if @results.present? %>
    <% @results.each do |artist| %>
      <div class="artist"> 

      <%= link_to image_tag(artist.image, class: "artist-img"), artist_path(artist.id) if artist.image.attached? %>

      <p class="property">name: <span class="bold"><%= artist.artist_name %></span></p>

      </div>
    <% end %>
  <% else %>
    <div class="content-non">該当する検索結果はありません。</div>
  <% end %>
</div>

</div>

<%= render "shared/footer" %>

app/views/artists/show.html.erb
<%= render "shared/second-header" %>

<div id="artist-show-background-image">

<div class="artist-page-title">ARTIST PROFILE</div>

<div class="artist-profile">
  <div>
  <%= image_tag(@artist.image, class: "artist-profile-img") if @artist.image.attached? %>
  <div>
    <% if user_signed_in? && current_user.id == @artist.user.id %>
      <%= link_to 'アーティスト情報の編集', edit_artist_path(@artist.id), class: "artist-show-btn" %>
    <% end %>
  </div>
  </div>
  <div>
    <div class="artist-profile-content">
      <div class="artist-profile-text">アーティスト名</div>
      <div class="artist-name-textarea"><%= @artist.artist_name %></div>
    </div>

    <div class="artist-profile-content">
      <div class="artist-profile-text">所属</div>
      <div class="affiliation-textarea"><%= @artist.affiliation %></div>
    </div>

    <div class="artist-profile-content">
      <div class="artist-profile-text">経緯・経歴</div>
      <div class="personal-history-textarea"><%= @artist.personal_history %></div>
    </div>

    <div class="artist-profile-content">
      <div class="artist-profile-text">支援活動に興味を持った理由</div>
      <div class="reason-for-support-activities-textarea"><%= @artist.reason_for_support_activities %></div>
    </div>

    <div class="artist-profile-content">
      <div class="artist-profile-text">メッセージ</div>
      <div class="artist-message-textarea"><%= @artist.artist_message %></div>
    </div>
  </div>
</div>
<br>
<br>

<div class="this-artist-artwork">THIS ARTIST'S ARTWORK</div>

<div class="artist-artworks-grid">
  <% if @artworks.present? %>
    <% @artworks.each do |artwork| %>
      <div class="artist-artwork"> 

      <%= link_to image_tag(artwork.image, class: :"artist-artwork-img"), artwork_path(artwork.id)%>

      <p class="property">title: <span class="bold"><%= artwork.title %></span></p>
      <p class="property">¥ <span class="bold"><%= artwork.price %></span></p>
      <p class="property">favorite: <span class="bold"><%= Favorite.where(artwork_id: artwork.id).count %></span></p>

      <% if nil != Order.find_by(artwork_id: artwork.id)%>
        <div class="content-non">Sold Out!!</div>
      <% end %>
       </div>
    <% end %>
  <% else %>
  <div class="artist-artwork-non">作品が登録されていません。</div>
  <% end %>
</div>
  

<br>
<div class="this-artist-artwork">THIS ARTIST'S SUPPORT PROJECT</div>
<br>

<div class="artist-select-project">
  <div class="artist-project">

    <br>
    <p class="donation-property">project: <span class="project-bold"><%= @donation_project.project_name %></span></p>
    <br>

    <%= image_tag(@donation_project.image, class: "donation-project-img") if @donation_project.image.attached? %>

    <div class="project-textarea"><span class="donation-property">text: <%= @donation_project.text %></span></div>

    <table class="tableArea" id="makeImg">
      <tr>
        <th>目標金額</th><th>現在までの支援金総額</th><th>プロジェクト達成までの残り金額</th>
      </tr>
      <tr>
        <td><span class="donation-credit"><%= @donation_project.target_amount %></span></td><td><span class="donation-credit"><%= @donation_project.current_amount %></span></td>

        <% if 0 < @donation_project.target_amount - @donation_project.current_amount %>
        <td><span class="donation-credit"><%= @donation_project.target_amount - @donation_project.current_amount %></span></td>
        <% else %>
        <td><span class="donation-credit"><%= 0 %></span></td>
        <% end %>
        
      </tr>
    </table>

    <% if @donation_project.current_amount >= @donation_project.target_amount %>
      <div class="content-non">このプロジェクトは達成されました。ご協力ありがとうございました!!!</div>
    <% end %>
  </div>
</div>

</div>

<%= render "shared/footer" %>