config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "artworks#index"

  resources :cards, only: [:new, :create, :destroy]

  resources :contacts, only: [:index]

  resources :donation_projects, only: [:index, :new, :create]

  resources :users, only: [:show] do
    member do
      get 'favorite'
    end
  end

  resources :artists, only: [:index, :new, :create, :edit, :update, :show] do
    collection do
      post 'search'
    end
  end

  resources :artworks do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
  end

  resources :donation_project_rooms, only: [:show] do
    resources :room_messages, only: [:create]
  end

  mount ActionCable.server => '/cable' #追加
  
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :artist
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_one :order

  belongs_to_active_hash :category
  belongs_to_active_hash :main_color
  belongs_to_active_hash :motif
  belongs_to_active_hash :feeling
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :scheduled_delivery

  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :size
    validates :text
    validates :price, inclusion: { in: 1000..9999999, message: 'は範囲内の数値を入力してください' }, format: { with: /\A[0-9]+\z/, message: 'は半角数字で入力してください' }
    validates :category_id,             numericality: { other_than: 0, message: 'を選択してください' }
    validates :main_color_id,           numericality: { other_than: 0, message: 'を選択してください'  }
    validates :motif_id,                numericality: { other_than: 0, message: 'を選択してください'  }
    validates :feeling_id,              numericality: { other_than: 0, message: 'を選択してください'  }
    validates :prefecture_id,           numericality: { other_than: 0, message: 'を選択してください'  }
    validates :scheduled_delivery_id,   numericality: { other_than: 0, message: 'を選択してください'  }
    validates :image, presence: { message: 'を選択してください' }
    
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_artwork, only: [:edit, :show, :update, :destroy]
  before_action :search_artwork, only: [:index, :search, :show]

  def index
    @artworks = Artwork.all.order(created_at: "DESC")
    
  end

  def new
    @artwork = Artwork.new
    @donation_project = DonationProject.find_by(id: current_user.artist.donation_project_id)

  end

  def create
    @artwork = Artwork.new(artwork_params)
    
    if @artwork.valid?
      @artwork.save
      redirect_to root_path
      
    else
      @donation_project = DonationProject.find_by(id: current_user.artist.donation_project_id)
      render :new
      
    end
  end

  def edit
    unless current_user.id == @artwork.artist.user.id
      redirect_to root_path

    end

    @donation_project = DonationProject.find_by(id: current_user.artist.donation_project_id)
    
  end

  def update
    if @artwork.update(artwork_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @artwork.artist.user.id
      @artwork.destroy
      redirect_to root_path

    else
      redirect_to root_path

    end
  end

  def show
    @artist = Artist.find_by(id: @artwork.artist.id)

    @comment = Comment.new
    @comments = @artwork.comments.includes(:user)

    #作品の設定金額から寄付される金額を計算
    donationPrice = @artwork.price * 0.9
    @donationPrice = donationPrice.floor

    #作品のお気に入り登録数を計算
    @favoriteCount = Favorite.where(artwork_id: @artwork.id).count

  end

  def search

    #検索結果を変数に格納
    @results = @a.result
    
  end

  private

  def artwork_params
    params.require(:artwork).permit(:title, :size, :text, :price, :category_id, :main_color_id, :motif_id, :feeling_id, :prefecture_id, :scheduled_delivery_id, :image).merge(artist_id: current_user.artist.id)
  end

  def set_artwork
    @artwork = Artwork.find(params[:id])
  end

  def search_artwork

    # 検索オブジェクトを生成
    @a = Artwork.ransack(params[:q])  

    #ActiveHachに定義されたidが０以外の各値を変数に格納
    @category = Category.where.not(id: 0)
    @main_color = MainColor.where.not(id: 0)
    @motif = Motif.where.not(id: 0)
    @feeling = Feeling.where.not(id: 0)
  end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/edit.html.erb
<%= render "shared/second-header" %>

<div id="artwork-edit-background-image">

  <div class="artwork-contents">
    <div class="svgSample1">
    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
      <defs>
        <text dy="0.4em" id="outTextx">作品情報編集</text>
      </defs>
      <use x="50%" y="50%" xlink:href="#outTextx"></use>
      <use x="50%" y="50%" xlink:href="#outTextx"></use>
    </svg>
    </div>

    作品情報を編集しましょう。作品が購入された場合、指定している支援プロジェクトに売り上げ金額の90%が寄付されます。

  <%= form_with model: @artwork, local: true do |f| %>

    <%= render 'shared/error_messages', model: @artwork %>
  <div class="form-content">
    <div class="field">
    <%= f.label :image, "作品写真" , class:"label"%><br />
    <%= f.file_field :image, id:"content-image" %>
    <div id="image-list"></div>
    </div>

    <div class="field">
    <%= f.label :title, "作品タイトル" , class:"label"%><br />
    <%= f.text_area :title, class:"title-textarea", id:"item-name", placeholder:"作品タイトル（必須 15文字まで)", maxlength:"15" %>
    </div>

    <div class="field">
    <%= f.label :text, "作品の説明" , class:"label"%><br />
    <%= f.text_area :text, class:"text-textarea", id:"item-name", placeholder:"作品の説明（須必 150文字まで)", maxlength:"150" %>
    </div>

    <div class="field">
    <%= f.label :size, "サイズ" , class:"label"%><br />
    <%= f.text_field :size, class:"size-textarea", id:"item-name", placeholder:"例) h240mm × w120mm", maxlength:"15" %>
    </div>

    <div class="field">
    <%= f.label :category_id, "カテゴリー" , class:"label"%><br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
    <%= f.label :main_color_id, "メインカラー" , class:"label"%><br />
    <%= f.collection_select(:main_color_id, MainColor.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
    <%= f.label :motif_id, "モチーフ" , class:"label"%><br />
    <%= f.collection_select(:motif_id, Motif.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
    <%= f.label :feeling_id, "フィーリング" , class:"label"%><br />
    <%= f.collection_select(:feeling_id, Feeling.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
    <%= f.label :prefecture_id, "発送元の地域" , class:"label"%><br />
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
    <%= f.label :scheduled_delivery_id, "発送日の目安" , class:"label"%><br />
    <%= f.collection_select(:scheduled_delivery_id, ScheduledDelivery.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

  <div class="field">
    <%= f.label :price, "設定価格" , class:"label"%><br />
    <div class="weight-bold-text question-text">
      <span class="sell-price">(¥1000〜9,999,999)</span>
    </div>
    <%= f.text_field :price, class:"price-textarea", id:"artwork-price", placeholder:"例）1000" %>
  </div>
    <div class="sell-price">
    <div class="price-content">
            <span>販売手数料 (10%)</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span><%= @donation_project.project_name %>への寄付金額</span>
            <span>
              <span id='donation'></span>円
          </div>
          </span>
        </div>
      
    <%= f.submit "登録する" ,class:"submit-btn" %>

  <% end %>
  </div>

</div>

<%= render "shared/footer" %>

app/views/artworks/index.html.erb
<%= render "shared/header" %>

<div id="artwork-index-background-image">

<div class="page-title">ARTWORKS</div>

<div class="grid">
  <% if @artworks.present? %>
    <% @artworks.each do |artwork| %>
      <div class="artwork"> 
    
      <%= link_to image_tag(artwork.image, class: "artwork-img"), artwork_path(artwork.id) if artwork.image.attached? %>

      <p class="property">title: <span class="bold"><%= artwork.title %></span></p>
      <p class="property">¥ <span class="bold"><%= artwork.price %></span></p>
      <p class="property">favorite: <span class="bold"><%= Favorite.where(artwork_id: artwork.id).count %></span></p>
      <% if nil != Order.find_by(artwork_id: artwork.id)%>
        <div class="content-non">Sold Out!!</div>
      <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="content-non">アートワークが登録されていません。</div>
  <% end %>
</div>

</div>

<%= render "shared/footer" %>

app/views/artworks/new.html.erb
<%= render "shared/second-header" %>

<div id="artwork-new-background-image">

  <div class="artwork-contents">
    <div class="svgSample1">
    <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
      <defs>
        <text dy="0.4em" id="outTextx">作品情報登録</text>
      </defs>
      <use x="50%" y="50%" xlink:href="#outTextx"></use>
      <use x="50%" y="50%" xlink:href="#outTextx"></use>
    </svg>
    </div>

    作品情報を入力しましょう。作品が購入された場合、指定している支援プロジェクトに売り上げ金額の90%が寄付されます。

    <%= form_with model: @artwork, local: true do |f| %>

    <%= render 'shared/error_messages', model: @artwork %>

    <div class="field">
    <%= f.label :image, "作品写真" , class:"label"%><br />
    <%= f.file_field :image, id:"content-image" %>
    </div>

    <div id="image-list"></div>

    <div class="field">
    <%= f.label :title, "作品タイトル" , class:"label"%><br />
    <%= f.text_area :title, class:"title-textarea", id:"item-name", placeholder:"作品タイトル（必須 15文字まで)", maxlength:"15" %>
    </div>

    <div class="field">
    <%= f.label :text, "作品の説明" , class:"label"%><br />
    <%= f.text_area :text, class:"text-textarea", id:"item-name", placeholder:"作品の説明（必須 150文字まで)", maxlength:"150" %>
    </div>

    <div class="field">
    <%= f.label :size, "サイズ" , class:"label"%><br />
    <%= f.text_field :size, class:"size-textarea", id:"item-name", placeholder:"例) h240mm × w120mm", maxlength:"15" %>
    </div>

    <div class="field">
    <%= f.label :category_id, "カテゴリー" , class:"label"%><br />
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
    <%= f.label :main_color_id, "メインカラー" , class:"label"%><br />
    <%= f.collection_select(:main_color_id, MainColor.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
    <%= f.label :motif_id, "モチーフ" , class:"label"%><br />
    <%= f.collection_select(:motif_id, Motif.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
    <%= f.label :feeling_id, "フィーリング" , class:"label"%><br />
    <%= f.collection_select(:feeling_id, Feeling.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
    <%= f.label :prefecture_id, "発送元の地域" , class:"label"%><br />
    <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
    <%= f.label :scheduled_delivery_id, "発送日の目安" , class:"label"%><br />
    <%= f.collection_select(:scheduled_delivery_id, ScheduledDelivery.all, :id, :name, {}, {class:"select-box", id:"artwork-category"}) %>
    </div>

    <div class="field">
      <%= f.label :price, "設定価格" , class:"label"%><br />
      <div class="weight-bold-text question-text">
        <span class="sell-price">(¥1,000〜9,999,999)</span>
      </div>
      <%= f.text_field :price, class:"price-textarea", id:"artwork-price", placeholder:"例）1000" %>
    </div>
    <div class="sell-price">
      <div class="price-content">
        <span>販売手数料 (10%)</span>
        <span>
          <span id='add-tax-price'></span>円
        </span>
      </div>
      <div class="price-content">
        <span><%= @donation_project.project_name %>への寄付金額</span>
        <span>
          <span id='donation'></span>円
      </div>
      </span>
    </div>
        
      <%= f.submit "登録する" ,class:"submit-btn" %>

    <% end %>
  </div>

</div>

<%= render "shared/footer" %>

app/views/artworks/search.html.erb
<%= render "shared/header" %>

<div id="artwork-search-background-image">

<div class="page-title">ARTWORKS SEARCH RESULT</div>

<div class="grid">
  <% if @results.present? %>
    <% @results.each do |artwork| %>
      <div class="artwork"> 
    
      <%= link_to image_tag(artwork.image, class: "artwork-img"), artwork_path(artwork.id) if artwork.image.attached? %>

      <p class="property">title: <span class="bold"><%= artwork.title %></span></p>
      <p class="property">¥ <span class="bold"><%= artwork.price %></span></p>
      <p class="property">favorite: <span class="bold"><%= Favorite.where(artwork_id: artwork.id).count %></span></p>
      <% if nil != Order.find_by(artwork_id: artwork.id)%>
          <div class="content-non">Sold Out!!</div>
      <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="content-non">該当する検索結果はありません。</div>
  <% end %>
</div>

</div>

<%= render "shared/footer" %>

app/views/artworks/show.html.erb
<%= render "shared/second-header" %>

<div id="artist-show-background-image">

<div class="artwork-page-title">ARTWORK DETAIL</div>

<div class="artwork-detail">
  <div>
  <%= image_tag(@artwork.image, class: "artwork-detail-img") if @artwork.image.attached? %>
  <div>

  <div class="star">
  <% if user_signed_in? %>
  <div id="artwork" data-id=<%= @artwork.id %> <% if nil != Favorite.find_by(user_id: current_user.id, artwork_id: @artwork.id) %>data-check="true"<% end %> >
    <%= image_tag "star.png", class:"star-icon" %>
  </div>
  <% end %>
    お気に入り登録数 <span id="count"><%= @favoriteCount %></span>
    
    <% if user_signed_in? && current_user.id == @artwork.artist.user.id && nil == Order.find_by(artwork_id: @artwork.id) %>
      <%= link_to '作品情報の編集', edit_artwork_path(@artwork.id), method: :get, class:"artwork-show-btn" %>
      <%= link_to '削除', artwork_path(@artwork.id), method: :delete, class:'artwork-show-btn' %>
    <% end %>
  </div>

    <% if nil != Order.find_by(artwork_id: @artwork.id) %>
        <div class="artwork-content-non">Sold Out!!</div>
    <% elsif @artist.donation_project.current_amount >= @artist.donation_project.target_amount %>
        <div class="artwork-project-non">この作品のアーティストが支援しているプロジェクトは終了しています。</div>
    <% elsif nil == Order.find_by(artwork_id: @artwork.id) && user_signed_in? && current_user.id != @artwork.artist.user.id %>
      <span class="artwork-donation-call">この作品を購入すると<%= @artist.donation_project.project_name %>に¥<%= @donationPrice %>円寄付されます。</span>
      <br>
      <%= link_to '購入画面に進む', artwork_orders_path(@artwork.id) ,class:"artwork-show-btn"%>
    <% end %>

  </div>
  </div>
  <div>
    <div class="artwork-detail-content">
      <div class="artwork-detail-text">タイトル</div>
      <div class="artwork-title-textarea"><%= @artwork.title %></div>
    </div>

    <div class="artwork-detail-content">
      <div class="artwork-detail-text">アーティスト名</div>
      <div class="artwork-artist-name-textarea"><%= link_to @artwork.artist.artist_name, artist_path(@artwork.artist.id), method: :get, class: "artwork-artist-btn" %></div>
    </div>

    <div class="artwork-detail-content">
      <div class="artwork-detail-text">作品の説明</div>
      <div class="artwork-text-textarea"><%= @artwork.text %></div>
    </div>

    <div class="artwork-detail-content">
      <div class="artwork-detail-text">サイズ</div>
      <div class="artwork-size-textarea"><%= @artwork.size %></div>
    </div>

    <div class="artwork-detail-content">
      <div class="artwork-detail-text">設定金額</div>
      <div class="artwork-price-textarea"><%= @artwork.price %></div>
    </div>

    <div class="artwork-detail-content">
      <div class="artwork-detail-text">カテゴリー</div>
      <div class="artwork-category-textarea"><%= @artwork.category.name %></div>
    </div>

    <div class="artwork-detail-content">
      <div class="artwork-detail-text">メインカラー</div>
      <div class="artwork-main-color-textarea"><%= @artwork.main_color.name %></div>
    </div>

    <div class="artwork-detail-content">
      <div class="artwork-detail-text">モチーフ</div>
      <div class="artwork-motif-textarea"><%= @artwork.motif.name %></div>
    </div>

    <div class="artwork-detail-content">
      <div class="artwork-detail-text">フィーリング</div>
      <div class="artwork-feeling-textarea"><%= @artwork.feeling.name %></div>
    </div>

    <div class="artwork-detail-content">
      <div class="artwork-detail-text">発送元の地域</div>
      <div class="artwork-prefecture-textarea"><%= @artwork.prefecture.name %></div>
    </div>

    <div class="artwork-detail-content">
      <div class="artwork-detail-text">発送までの日数</div>
      <div class="artwork-scheduled-delivery-textarea"><%= @artwork.scheduled_delivery.name %></div>
    </div>
  </div>
</div>

<div class="comment-area">
  <div class="comment-form">
    <% if user_signed_in? %>
      <%= form_with model: [@artwork, @comment], local: true do |f| %>

      <%= render 'shared/error_messages', model: @comment %>

        <div class="field">
          <%= f.label :text, "コメント" %><br />
          <%= f.text_field :text %>
          <%= f.submit "送信する" %>
        </div>
      <% end %> 
    <% end %>
  </div>

  <ul class="comments_lists">
    
    <div id="comments">
    <% @comments.reverse_each do |comment| %>
      <li class="comments_list">
        <span class="comment-people">
          <% if nil == Artist.find_by(user_id: comment.user.id) %>
          <%= comment.user.nickname %>
          <% else %>
          <%= link_to comment.user.artist.artist_name, artist_path(comment.user.artist.id), class:"comment-btn" %>
          <% end %>
        </span>
        <span class="comment-text">
          <%= comment.text %>
        </span>
        <span class="comment-created">
          <%= l comment.created_at %>
        </span>
        <br>
      </li>
    <% end %>
    </div>
  </ul>
</div>

</div>
          
<%= render "shared/footer" %>