config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "artworks#index"

  resources :cards, only: [:new, :create, :destroy]

  resources :contacts, only: [:index]

  resources :donation_projects, only: [:index, :new, :create]

  resources :users, only: [:show] do
    member do
      get 'favorite'
    end
  end

  resources :artists, only: [:index, :new, :create, :edit, :update, :show] do
    collection do
      post 'search'
    end
  end

  resources :artworks do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
  end

  resources :donation_project_rooms, only: [:show] do
    resources :room_messages, only: [:create]
  end

  mount ActionCable.server => '/cable' #追加
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites
  has_many :artworks, through: :favorites
  has_many :comments
  has_many :orders
  has_one :artist
  has_one :card, dependent: :destroy

  VALID_ZENKAKU_REGEX = /\A[ぁ-んァ-ン一-龥]/.freeze
  VALID_KATAKANA_REGEX = /\A[ァ-ヶー－]+\z/.freeze
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])/.freeze

  with_options presence: true do
    validates :nickname, uniqueness: true
    validates :last_name, format: { with: VALID_ZENKAKU_REGEX, message: 'は全角(漢字・ひらがな・カタカナ)で入力してください' }
    validates :first_name, format: { with: VALID_ZENKAKU_REGEX, message: 'は全角(漢字・ひらがな・カタカナ)で入力してください' }
    validates :last_name_kana, format: { with: VALID_KATAKANA_REGEX, message: 'は全角(カタカナ)で入力してください' }
    validates :first_name_kana, format: { with: VALID_KATAKANA_REGEX, message: 'は全角(カタカナ)で入力してください' }
    validates :birth_date
  end

  validates :password, format: { with: VALID_PASSWORD_REGEX, message: "は半角英数字混合で入力してください" }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :search_artwork, only: [:show]

  def show

    @user = User.find(params[:id])

    unless current_user.id == @user.id
      redirect_to root_path

    end

    #ユーザーのidと関連する中間テーブルのレコードを全て取得
    favorites = Favorite.where(user_id: @user.id)

    @favorite_artworks = []

    #先ほど取得した中間テーブルのレコードと関連するartworkのレコードを全て取得
    favorites.each do |favorite| 
      @favorite_artworks.push(Artwork.find_by(id: favorite.artwork_id))
  
    end

    #環境変数を読み込む
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]

    #ユーザーのカード情報を取得
    @card = Card.find_by(user_id: current_user.id)

    if @card != nil

      # 先程のカード情報を元に、顧客情報を取得
      customer = Payjp::Customer.retrieve(@card.customer_token) 
      @card = customer.cards.first

    end
  end

  #お気に入り登録、または削除を行うメソッド
  def favorite
    artwork = Artwork.find(params[:id])

    #特定の組み合わせを中間テーブルから検索
    favorite = Favorite.find_by(user_id: current_user.id, artwork_id: artwork.id)

    #中間テーブルのレコードを作成したか削除したかを判別する変数を定義
    isfavorite = false

    if favorite == nil

      #検索した組み合わせが中間テーブルに存在しなかった場合、保存を行う
      Favorite.new(user_id: current_user.id, artwork_id: artwork.id).save
      
      isfavorite = true

    else

      #検索した組み合わせが既に中間テーブルに存在していた場合、削除を行う
      favorite.delete

    end

    #前のページのurlから実行する処理を分岐
    if request.referer&.include?("artwork") 
      render json: { or: isfavorite } #artwork詳細画面
    
    else
      redirect_to user_path(current_user.id) #ユーザー詳細画面
      
    end 
  end

  private

  def search_artwork

    # 検索オブジェクトを生成
    @a = Artwork.ransack(params[:q]) 

    #ActiveHachに定義されたidが０以外の各値を変数に格納
    @category = Category.where.not(id: 0)
    @main_color = MainColor.where.not(id: 0)
    @motif = Motif.where.not(id: 0)
    @feeling = Feeling.where.not(id: 0)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/second-header" %>

<div id="user-show-background-image">

<div class="user-page-title">USER MY</div>
<br>
<br>
<br>
<div class="info">
  <div class="card-info">
    <div class="card-info-title">CARD INFO</div>
    <br>
    <% if @card != nil %>
      【カード番号】
      <br>
      <%= "**** **** **** " + @card[:last4] %>
      <%# カード番号の下4桁を取得 %>
      <br>
      【有効期限】
      <br>
      <%= @card[:exp_month] %>
      <%# 有効期限の「月」を取得 %>
      /
      <%= @card[:exp_year] %>
      <%# 有効期限の「年」を取得 %>
    <br>
    <%= link_to '削除', card_path(@card.id), method: :delete, class: "user-show-btn" %>
    <% else %>
    <%= link_to 'カード情報登録', new_card_path, class: "user-show-btn" %>
    <% end %>
  </div>
  <div class~="user-info">
    <div class="user-info-title">USER INFO</div>
    <br>
      【nickname】
    <br>
      <%= @user.nickname %>
    <br>
      【e-mail】
    <br>
      <%= @user.email %>
    <br>
  </div>
</div>

<br>
<br>
<br>
<br>
<div class="this-users-favorite">THIS USER'S FAVORITE</div>

<div class="user-favorites-grid">
  <% if @favorite_artworks.length != 0 %>
    <% @favorite_artworks.each do |favorite_artwork| %>

    <div class="user-favorite"> 

      <%= link_to image_tag(favorite_artwork.image, class: "artwork-img"), artwork_path(favorite_artwork.id) if favorite_artwork.image.attached? %>

      <p class="property">title: <span class="bold"><%= favorite_artwork.title %></span></p>
      <p class="property">¥ <span class="bold"><%= favorite_artwork.price %></span></p>
      <p class="property">favorite: <span class="bold"><%= Favorite.where(artwork_id: favorite_artwork.id).count %></span></p>

      <br>
      <%= link_to '削除', favorite_user_path(favorite_artwork.id), class:'user-show-btn' %>

    </div>
    <% end %>
  <% else %>
    <div class="content-non">お気に入り登録された作品はありません。</div>
  <% end %>
</div>

</div>

<%= render "shared/footer" %>