config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "artworks#index"

  resources :cards, only: [:new, :create, :destroy]

  resources :contacts, only: [:index]

  resources :donation_projects, only: [:index, :new, :create]

  resources :users, only: [:show] do
    member do
      get 'favorite'
    end
  end

  resources :artists, only: [:index, :new, :create, :edit, :update, :show] do
    collection do
      post 'search'
    end
  end

  resources :artworks do
    collection do
      get 'search'
    end
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
  end

  resources :donation_project_rooms, only: [:show] do
    resources :room_messages, only: [:create]
  end

  mount ActionCable.server => '/cable' #追加
  
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <%= link_to image_tag("artwork-donation-logo-white.png", class:"logo-white"), artworks_path %>
  <div class="wrapper">
    <P><small>&copy; 2020 artwork donation</small></p>
  </div>
</footer>

app/views/shared/_header.html.erb
<div id="header-background-image">

<div class="nav">
  <%= link_to image_tag("artwork-donation-logo.png", class:"logo-image"), artworks_path %>
  <div class="main-menu">
    <ul class="user-menu">
      <li><%= link_to '支援中のプロジェクト一覧', donation_projects_path, class: "btn" %></li>
      <li><%= link_to 'サポートアーティスト一覧', artists_path, class: "btn" %></li>
      <li><%= link_to '作品一覧', artworks_path, class: "btn" %></li>
      <li><%= link_to 'お問い合わせ', contacts_path, class: "btn" %></li>
      <% if user_signed_in? %>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "devise-btn" %></li> 
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "devise-btn" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "devise-btn" %></li>
      <% end %>
    </ul>

    <ul class="artist-menu">
      <% if user_signed_in? && current_user.admin?%>
      <li><%= link_to '支援プロジェクト登録', new_donation_project_path, class: "btn" %></li>
      <% end %>

      <% if user_signed_in? && nil != Artist.find_by(user_id: current_user.id) %>
      <li><%= link_to '作品登録', new_artwork_path, class: "btn" %></li>
      <li><%= link_to '支援プロジェクトチャットルーム', donation_project_room_path(current_user.artist.donation_project.id), class: "btn" %></li>
      <li><%= link_to current_user.artist.artist_name, artist_path(current_user.artist.id), class: "btn" %></li>
      <% elsif user_signed_in? %>
      <li><%= link_to 'サポートアーティスト登録', new_artist_path, class: "btn" %></li>
      <% end %>
      <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, user_path(current_user.id), class: "btn" %></li> 
      <% end %>
    </ul>
  </div>
</div>



<div class="header-content">

  <div class="slide" id="makeImg">
  <img src="assets/IMG_7892.jpg">
  <img src="assets/sandra-seitamaa-7-3cGWyQlV0-unsplash.jpg">
  <img src="assets/amauri-mejia-IhXrWDckZOQ-unsplash.jpg">
  <img src="assets/ravi-sharma-85IJIHk4-jc-unsplash.jpg">
  <img src="assets/Emma-Lindstrom-7.jpg">
  </div>

  <div class="artwork-search">
    <%= search_form_for @a, url: search_artworks_path do |f| %>

    <div class="header-artwork-form1">
      <div class="field">
      <%= f.label :name_eq, 'カテゴリー' %>
      <%= f.collection_select :category_id_eq, @category, :id, :name, include_blank: '--' %>
      </div>
      <br>

      <div class="field">
      <%= f.label :name_eq, 'メインカラー' %>
      <%= f.collection_select :main_color_id_eq, @main_color, :id, :name, include_blank: '--' %>
      </div>
      <br>
    </div>

    <div class="header-artwork-form2">
      <div class="field">
      <%= f.label :name_eq, 'モチーフ' %>
      <%= f.collection_select :motif_id_eq, @motif, :id, :name, include_blank: '--' %>
      </div>
      <br>

      <div class="field">
      <%= f.label :name_eq, 'フィーリング' %>
      <%= f.collection_select :feeling_id_eq, @feeling, :id, :name, include_blank: '--' %>
      </div>
      <br>
    </div>

      <div class="field">
      <%= f.label :price, '設定価格：' %>
      <%= f.radio_button :price_lteq, '' %>
      指定なし
      <%= f.radio_button :price_lteq, '1000' %>
      1000円以下
      <%= f.radio_button :price_lteq, '2500' %>
      2500円以下
      <%= f.radio_button :price_lteq, '5000' %>
      5000円以下
      <br>
      <%= f.submit '作品検索' , class: "submit-btn"%>
      </div>
    <% end %>
  </div>

  <div class="artist-search">
    <%= form_with url: search_artists_path, class:'form-wrap', local: true do |f| %>
      <div class='message-form'>
        <div class="message-field">
          <%= f.text_area :keyword, class:"input-message", placeholder: "keyword" %>
        </div>
      </div>
      <div class="submit-post">
        <%= f.submit "アーティスト検索", class: "submit-btn" %>
      </div>
    <% end %>
  </div>

</div>

</div>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/_second-header.html.erb
<div class="second-header">
  <div class="second-header-nav">
    <%= link_to image_tag("artwork-donation-logo-white.png", class:"second-header-logo"), artworks_path %>
    <div class="second-header-login">
      <% if user_signed_in? %>
        <%= link_to current_user.nickname, user_path(current_user.id), class: "second-header-btn"  %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "second-header-btn"  %> 
      <% else %>
        <%= link_to 'ログイン', new_user_session_path, class: "second-header-btn"  %>
        <%= link_to '新規登録', new_user_registration_path, class: "second-header-btn"  %>
      <% end %>
    </div>
  </div>
</div>